# Generated by Django 5.2.3 on 2025-07-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название столовой')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыто/Закрыто')),
            ],
            options={
                'verbose_name': 'Столовая',
                'verbose_name_plural': 'Столовые',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_available',
        ),
        migrations.AddField(
            model_name='order',
            name='canteen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.canteen', verbose_name='Столовая'),
        ),
        migrations.AddField(
            model_name='user',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='api.canteen', verbose_name='Столовая сотрудника'),
        ),
        migrations.CreateModel(
            name='CanteenDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Доступное количество')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.canteen')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
            ],
            options={
                'verbose_name': 'Блюдо в столовой',
                'verbose_name_plural': 'Блюда в столовых',
                'unique_together': {('canteen', 'dish')},
            },
        ),
    ]
