# Generated by Django 5.2.3 on 2025-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_canteen_remove_dish_is_available_order_canteen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приготовления'),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_type',
            field=models.CharField(choices=[('asap', 'Как можно скорее'), ('scheduled', 'Ко времени')], default='asap', max_length=10, verbose_name='Тип приготовления'),
        ),
    ]
